#!/bin/sh

if [ -f /etc/mysql/change_password ]; then
  rm -f /etc/mysql/change_password
  new_password=`pwgen -s 16`
  mysqladmin password $new_password
  echo -en "[client]\npassword=$new_password\n" > /root/.my.cnf
  chmod 700 /root/.my.cnf

  debian_mysql_password=`cat /etc/mysql/debian.cnf | grep password | head -n 1 | tr -d " " | cut -d = -f 2`
  new_password=`pwgen -s 16`
  sed -i "s/$debian_mysql_password/$new_password/" /etc/mysql/debian.cnf
  echo "update mysql.user set password=password('$new_password') where username = 'debian-sys-maint'; flush privileges;"

fi

